# Generated by Django 5.0.6 on 2024-05-21 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image_file',
            fields=[
                ('image_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.image')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='pin/')),
            ],
            bases=('api.image',),
        ),
        migrations.CreateModel(
            name='Image_url',
            fields=[
                ('image_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.image')),
                ('photo', models.URLField(blank=True, null=True)),
            ],
            bases=('api.image',),
        ),
        migrations.RemoveField(
            model_name='image',
            name='img_url',
        ),
        migrations.AddField(
            model_name='image',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='source',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
