# Generated by Django 5.0.6 on 2024-05-21 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_image_file_image_url_remove_image_img_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='is_url',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
